---
- name: Create Lighthouse directory
  become: true
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    recurse: yes
    mode: '0755'
    owner: ranel
    group: ranel
- name: Lighthouse | Clone from Git
  become: true
  ansible.builtin.git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    version: master
    dest: "/var/www/lighthouse"
    force: true
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify: restart-nginx